spring:
  kafka:
    bootstrap-servers: localhost:9092
    properties:
      schema.registry.url: http://localhost:8081
    producer:
      key-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
    consumer:
      key-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      properties:
        specific.avro.reader: true

spring:
  kafka:
    streams:
      application-id: vehicle-streams-app
      properties:
        processing.guarantee: exactly_once_v2
        schema.registry.url: http://localhost:8081
        default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
        default.value.serde: io.confluent.kafka.serializers.KafkaAvroSerde
        default.deserialization.exception.handler: com.example.kafka.StreamsDlqDeserializationHandler

ksqldb:
  host: localhost
  port: 8088
